apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75
---
loadBalancer:
  simple: LEAST_CONN
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: disable-mtls
  namespace: default
spec:
  mtls:
    mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: grpc-sidecar
  namespace: default
spec:
  ingress:
  - port:
      number: 50051
      protocol: HTTP2
    defaultEndpoint: unix:///var/run/svc.sock
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grpc-virtual-service
spec:
  hosts:
  - grpc-service
  gateways:
  - istio-ingressgateway
  http:
  - route:
    - destination:
        host: grpc-service.default.svc.cluster.local
        port:
          number: 50051
    retries:
      attempts: 3  # Retry failed requests
      perTryTimeout: 2s  # Timeout for each retry attempt
      retryOn: 5xx,connect-failure,refused-stream,unavailable
    timeout: 5s  # Overall timeout for requests
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grpc-connection-pool
  namespace: default
spec:
  host: grpc-service.default.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        http2MaxRequests: 1000  # Max concurrent gRPC requests (HTTP/2)
        maxRequestsPerConnection: 0  # Unlimited requests per connection (optimal for gRPC)
        idleTimeout: 30s  # Close idle connections after 30 seconds
      tcp:
        maxConnections: 2000  # Maximum TCP connections to the service
        connectTimeout: 2s  # Timeout for establishing new connections
---
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
